//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Build artifacts — not source, and not covered by tsconfig's project.
      '.output/**',
      '.nitro/**',
      '.tanstack/**',
      'dist/**',
      // Generated by `pnpm generate-routes`.
      'src/routeTree.gen.ts',
      // shadcn components are vendored upstream code; we don't reformat them.
      'src/components/ui/**',
    ],
  },
]
