#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Write to the jolt-server repo's own .env (this script lives in scripts/).
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

banner "Enable APNs push for Jolt pokes"

# ── Stage 1: Team ID ──────────────────────────────────────────────────────
stage "Apple: your Team ID"
say "Everything below happens in the Apple Developer account that owns the"
say "app installed on the phone. First we grab your Team ID."
open_url "https://developer.apple.com/account"
step "Sign in. On the Membership details page, find 'Team ID' (10 chars,"
step "letters+digits, e.g. XXXXXXXXXX)."
ask APNS_TEAM_ID "Paste your Team ID:"
write_env APNS_TEAM_ID "$APNS_TEAM_ID"

# ── Stage 2: App ID has Push enabled ──────────────────────────────────────
stage "Apple: confirm the App ID allows Push"
say "The bundle id must match the build on the phone and have the Push"
say "Notifications capability enabled. If you build under your own team it is"
say "your identifier, not cz.peelco.jolt."
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Open your app's Identifier. Under Capabilities, confirm 'Push"
step "Notifications' is checked (enable + Save if not)."
ask APNS_BUNDLE_ID "Bundle identifier [Enter for cz.peelco.jolt]:"
[[ -z "$APNS_BUNDLE_ID" ]] && APNS_BUNDLE_ID="cz.peelco.jolt"
write_env APNS_BUNDLE_ID "$APNS_BUNDLE_ID"

# ── Stage 3: create the APNs Auth Key (.p8) ───────────────────────────────
stage "Apple: create an APNs Auth Key"
warn "A Key (not a certificate). Apple lets you download the .p8 ONCE."
open_url "https://developer.apple.com/account/resources/authkeys/list"
step "Click + (Create a key). Name it e.g. 'Jolt APNs'."
step "Tick 'Apple Push Notifications service (APNs)', then Continue → Register."
step "Copy the Key ID shown (10 chars), then click Download to save the .p8."
note "Keep the .p8 somewhere safe; you cannot re-download it later."
ask APNS_KEY_ID "Paste the Key ID:"
write_env APNS_KEY_ID "$APNS_KEY_ID"

# ── Stage 4: store the .p8 + environment ──────────────────────────────────
stage "Server: store the key and choose the environment"
say "Point me at the .p8 you just downloaded; I'll fold it into one env line"
say "(newlines become literal \\n, which the server un-escapes)."
p8path=""
while :; do
  ask _P8PATH "Path to the downloaded .p8 file:"
  # Expand a leading ~ and surrounding quotes a human might paste.
  _P8PATH="${_P8PATH%\"}"; _P8PATH="${_P8PATH#\"}"
  _P8PATH="${_P8PATH/#\~/$HOME}"
  if [[ -f "$_P8PATH" ]]; then p8path="$_P8PATH"; break; fi
  warn "No file at that path — try again (or Ctrl-C to stop)."
done
# Join lines with a literal backslash-n (portable; the server un-escapes it).
APNS_KEY_P8="$(awk 'NR>1{printf "\\n"} {printf "%s", $0}' "$p8path")"
write_env APNS_KEY_P8 "$APNS_KEY_P8"
say ""
step "Environment: 'production' for a TestFlight/App Store build, 'sandbox'"
step "for a debug build run from Xcode. These do not interoperate."
ask APNS_ENV "APNS_ENV [Enter for production]:"
[[ -z "$APNS_ENV" ]] && APNS_ENV="production"
write_env APNS_ENV "$APNS_ENV"
warn "For the real deployment, copy these five APNS_* values into the"
warn "environment the server actually runs with (deploy/docker-compose.yml"
warn "reads them from the environment; in GitLab CI they are project variables)."

# ── Stage 5: restart + verify delivery ────────────────────────────────────
stage "Verify: restart and send a real poke"
say "Bring the server up with the new env, then prove it's talking to Apple"
say "and not the console stub."
note "Restart (in the directory with compose.yaml and .env):"
note "  docker compose up -d"
step "In the app, have a friend poke you (or poke a second test account)."
step "Watch the server logs. The stub prints lines beginning '[push] poke …'"
step "and 'would send 1 alert + 1 background push' — if you still see those,"
step "the APNS_* values didn't reach the running process."
note "A healthy delivery shows no ConsolePushSender lines; the recipient's"
note "phone gets the banner, and the poke's status moves off 'pending' once"
note "the device acks it."
if confirm "Did a poke deliver to the device (no stub log)?"; then
  say "${GREEN}Push is live.${RESET}"
else
  SKIPPED+=("Verify APNs delivery: check APNS_* reached the running server, the .p8/Key ID/Team ID match, and APNS_ENV matches the build (sandbox vs production).")
  warn "Recorded as unfinished — see the summary."
fi

finish
